### ISSUE TITLE
Depandabot alert

### ISSUE THREAD

**Issue by ghost** [Sthana-ai/get-environment#1]
Don't commit node_modules re.
Just use https://github.com/bahmutov/npm-install this will improve build and run times.

**Comment by ghost** [comment]
Doing an npm install is faster than github actions cloning your repo.

**Comment by dannypaul** [comment]
@pyros2097 this repository provides a JavaScript GitHub Action that is consumed by other repositories. It is not consuming a GitHub Action.

To create a [JavaScript GitHub Action](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github) as documented by GitHub, you must commit node_modules, with one alternative.

> From your terminal, commit your action.yml, index.js, node_modules, package.json, package-lock.json, and README.md files. If you added a .gitignore file that lists node_modules, you'll need to remove that line to commit the node_modules directory

The alternative to it is:

> As an alternative to checking in your node_modules directory you can use a tool called @vercel/ncc to compile your code and modules into one file used for distribution.

As of now we do not want to invest our time in the alternative.

Please re-direct your comments to GitHub, as this a part of the GitHub Actions API. 😄
